{
 "title": "OimClientTest",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Method0 TPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "query": "SELECT non_negative_derivative(max(\"value\"), 1s) FROM \"method_value\" WHERE (\"instance\" = 'method0' AND \"type\" = 'count') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" }
     ]
    }
   ]
  },
  {
   "title": "Method0 TPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "requestPerSecond",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "method0" }
     ]
    }
   ]
  },
  {
   "title": "Method0 Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/count(value)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "response_code" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "method0" }
     ]
    }
   ]
  },
  {
   "title": "Method0 Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "TP50",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "latency" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1d" }
     ]
    },
    {
     "alias": "TP90",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "latency" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1d" }
     ]
    }
   ]
  },
  {
   "title": "Method1 TPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" }
     ]
    }
   ]
  },
  {
   "title": "Method1 TPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "requestPerSecond",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "method1" }
     ]
    }
   ]
  },
  {
   "title": "Method1 Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/count(value)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "response_code" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "method1" }
     ]
    }
   ]
  },
  {
   "title": "Method1 Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "TP50",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "latency" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1d" }
     ]
    },
    {
     "alias": "TP90",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "latency" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1d" }
     ]
    }
   ]
  },
  {
   "title": "Method2 TPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" }
     ]
    }
   ]
  },
  {
   "title": "Method2 TPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "requestPerSecond",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "method2" }
     ]
    }
   ]
  },
  {
   "title": "Method2 Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/count(value)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "response_code" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "method2" }
     ]
    }
   ]
  },
  {
   "title": "Method2 Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "TP50",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "latency" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1d" }
     ]
    },
    {
     "alias": "TP90",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "method2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "latency" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1d" }
     ]
    }
   ]
  },
  {
   "title": "Combined Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "method_value",
     "query": "SELECT sum(\"value\") /count(value) FROM \"method_value\" WHERE (\"type\" = 'response_code') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/count(value)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "response_code" }
     ]
    }
   ]
  }
 ]
}